trigger:
- develop

pool:
  vmImage: 'windows-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

# Add your build steps here

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
    publishLocation: 'Container'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Free Trial(c8c6f4a8-117b-419c-9a1f-9ce584069d0b)'
    appType: 'webApp'
    appName: 'hotel-booking-system'
    package: '$(System.ArtifactsDirectory)/drop/**/*.zip'
    deploymentMethod: 'auto'
